### ISSUE TITLE
Minerdelight's Sticky Basket crash

### ISSUE THREAD

**Issue by DragonGirl7567** [SammySemicolon/MinersDelight#25]
The game crashed when I placed the Sticky Basket

Forge - 47.2.0
Miner's Delight +
miners_delight-1.20.1-1.2.2.jar
Farmer's Delight
FarmersDelight-1.20.1-1.2.3.jar

The game crashed whilst unexpected error
Error: java.lang.ClassCastException: class com.sammy.minersdelight.content.block.sticky_basket.StickyBasketBlockEntity cannot be cast to class vectorwing.farmersdelight.common.block.entity.BasketBlockEntity (com.sammy.minersdelight.content.block.sticky_basket.StickyBasketBlockEntity is in module miners_delight@1.20.1-1.2.1 of loader 'TRANSFORMER' @6475e778; vectorwing.farmersdelight.common.block.entity.BasketBlockEntity is in module farmersdelight@1.20.1-1.2.3 of loader 'TRANSFORMER' @6475e778)

**Comment by theivycoder** [comment]
I have just encountered the same bug in 1.19.2

**Comment by SammySemicolon** [comment]
Could you send me your latest.log file?

**Comment by DragonGirl7567** [comment]
sorry I didn't give the log.

had trouble trying to create the crash to happen again cause it now freezes and does not crash right away.

I use the output log to copy the error part, hope that helps at the moment


Unreported exception thrown!
java.lang.ClassCastException: class com.sammy.minersdelight.content.block.sticky_basket.StickyBasketBlockEntity cannot be cast to class vectorwing.farmersdelight.common.block.entity.BasketBlockEntity (com.sammy.minersdelight.content.block.sticky_basket.StickyBasketBlockEntity is in module miners_delight@1.20.1-1.2.1 of loader 'TRANSFORMER' @6475e778; vectorwing.farmersdelight.common.block.entity.BasketBlockEntity is in module farmersdelight@1.20.1-1.2.3 of loader 'TRANSFORMER' @6475e778)
	at TRANSFORMER/miners_delight@1.20.1-1.2.1/com.sammy.minersdelight.content.block.sticky_basket.StickyBasketBlockEntity.<init>(StickyBasketBlockEntity.java:31)
	at TRANSFORMER/miners_delight@1.20.1-1.2.1/com.sammy.minersdelight.repack.registrate.builders.BlockEntityBuilder.lambda$createEntry$2(BlockEntityBuilder.java:139)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.entity.BlockEntityType.m_155264_(BlockEntityType.java:92)
	at TRANSFORMER/miners_delight@1.20.1-1.2.1/com.sammy.minersdelight.content.block.sticky_basket.StickyBasketBlock.m_142194_(StickyBasketBlock.java:181)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.chunk.LevelChunk.m_6978_(LevelChunk.java:263)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.m_6933_(Level.java:219)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.multiplayer.ClientLevel.m_6933_(ClientLevel.java:159)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.m_7731_(Level.java:196)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.BlockItem.m_7429_(BlockItem.java:163)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.BlockItem.m_40576_(BlockItem.java:68)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.BlockItem.m_6225_(BlockItem.java:46)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.ItemStack.lambda$useOn$3(ItemStack.java:246)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.ItemStack.onItemUse(ItemStack.java:261)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.ItemStack.m_41661_(ItemStack.java:246)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233746_(MultiPlayerGameMode.java:339)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233740_(MultiPlayerGameMode.java:291)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233729_(MultiPlayerGameMode.java:250)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233732_(MultiPlayerGameMode.java:290)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91277_(Minecraft.java:1698)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1976)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1795)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1112)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.main.Main.main(Main.java:218)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.0/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.0/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.0/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)

**Comment by DragonGirl7567** [comment]
got it

[crash-2024-01-11_18.37.58-client.txt](https://github.com/SammySemicolon/MinersDelight/files/13909533/crash-2024-01-11_18.37.58-client.txt)

**Comment by SammySemicolon** [comment]
Does this happen with just MD and FD ? As is this error is complete nonsense sadly

**Comment by DragonGirl7567** [comment]
Not just MD and FD. I have a Ton of mods downloaded. I with trial and error with what might be problem (have a first guess at moment)

**Comment by SammySemicolon** [comment]
If you figure it out, let me know, it feels like it'd be a mod conflict, some other mod adding functionality related to the basket and not realizing that the basket and sticky basket are two different things.

**Comment by DragonGirl7567** [comment]
Found the issue, it is with the mod Create Central Kitchen. not sure if your side, their side or a combined effort, sorry to bother

**Comment by SammySemicolon** [comment]
Don't worry, could you leave a github report over on their side? We'll sort it out

**Comment by DragonGirl7567** [comment]
ok

**Comment by GuaGuaGua-ua** [comment]
> TRANSFORMER

i have same question
